### PR TITLE
Gh-pages

### PR DESCRIPTION
**Pull request by BD103**
Hey. Can we use Github pages instead of replit for this?
It allows us to use markdown files instead of coding a backend.

### CODE REVIEW

**Comment by BD103** [comment]
Nevermind just read in the discussions section what you are actually trying to do :P

**Comment by whippingdot** [comment]
> Nevermind just read in the discussions section what you are actually trying to do :P

Why, what did we write there??

**Comment by BD103** [comment]
@whippingdot You guys were going to design a website where we can assign jobs to people, right?

**Comment by whippingdot** [comment]
No, I didn't say anything like that. @Isaiah08-D was the person who created this without telling me.

**Comment by BD103** [comment]
Ok. I'm creating a new discussion in the Discussions repo for some repo rules. If you could look over it in a few minutes then that would be awesome.

**Comment by Isaiah08-D** [comment]
Sorry, i didn't realize that i had to get approval before making a repo. I will next time!

**Pull request closed without merging**
